services:
  postgres:
    mem_limit: 256m

  fault-injector-server:
    mem_limit: 512m
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"

  billing-a:
    mem_limit: 512m
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"

  billing-b:
    mem_limit: 512m
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"

  catalog-a:
    mem_limit: 512m
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"

  catalog-b:
    mem_limit: 512m
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"
