<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mta.faultinjector</groupId>
    <artifactId>fault-injector-platform-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>fault-injector-platform-parent</name>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <modules>
        <module>fault-injector-server</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <fault-injector.version>0.0.1-SNAPSHOT</fault-injector.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.mta.faultinjector</groupId>
                <artifactId>fault-injector-protocol</artifactId>
                <version>${fault-injector.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
